//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Courses()
        {
            this.Selected_Category = new HashSet<Selected_Category>();
            this.SubCourse = new HashSet<SubCourse>();
        }
    
        public int CourseID { get; set; }
        public int UserID { get; set; }
        public string CourseName { get; set; }
        public Nullable<int> Price { get; set; }
        public string ShortDescription { get; set; }
        public Nullable<int> NumberOfStudents { get; set; }
        public string CourseLevel { get; set; }
        public string CourseStatus { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public string ImageName { get; set; }
        public string Text { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Discount Discount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Selected_Category> Selected_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubCourse> SubCourse { get; set; }
    }
}
