//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public int NotificationID { get; set; }
        public int UserID { get; set; }
        public string NotificationTitle { get; set; }
        public string NotificationText { get; set; }
        public System.DateTime NotificationDate { get; set; }
        public bool IsRead { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
